# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user_id',
            new_name='user',
        ),
    ]
